### ISSUE TITLE
handle key error better in transformation when key is not found 

### ISSUE THREAD

**Issue by ifenty** [ECCO-GROUP/ECCO-pipeline#43]
during transformation, I see the following error 

need to catch the keyerror and print out some better information about the error.
Is this information caught in the log?  

```
ERROR] 2023-10-16 10:22:15,189 - Transformation failed: 'confidence_level'
Traceback (most recent call last):
  File "/home/ep/miniconda3/envs/ecco_pipeline/lib/python3.10/site-packages/xarray/core/dataset.py", line 1353, in _construct_dataarray
    variable = self._variables[name]
KeyError: 'confidence_level'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/net/b230-304-t3/ecco_nfs_1/shared/ECCO-pipeline-ep/ECCO-pipeline/ecco_pipeline/transformations/transformation.py", line 250, in transform
    field_DA = self.perform_mapping(ds, factors, data_field_info, model_grid)
  File "/net/b230-304-t3/ecco_nfs_1/shared/ECCO-pipeline-ep/ECCO-pipeline/ecco_pipeline/transformations/transformation.py", line 166, in perform_mapping
    orig_data = ds[data_field].values
  File "/home/ep/miniconda3/envs/ecco_pipeline/lib/python3.10/site-packages/xarray/core/dataset.py", line 1444, in __getitem__
    return self._construct_dataarray(key)
  File "/home/ep/miniconda3/envs/ecco_pipeline/lib/python3.10/site-packages/xarray/core/dataset.py", line 1355, in _construct_dataarray
    _, name, variable = _get_virtual_variable(self._variables, name, self.dims)
  File "/home/ep/miniconda3/envs/ecco_pipeline/lib/python3.10/site-packages/xarray/core/dataset.py", line 185, in _get_virtual_variable
    raise KeyError(key)
KeyError: 'confidence_level'

**Comment by kevinmarlis** [comment]
`confidence_level` is a variable that we have defined in `AMSR-2_OSI-408` and `SSMIS_OSI-401-b`. I'll look into which dataset is causing this issue, hopefully it will be resolved by updating 401-b to 401-d (see #31 ). 

Either way this error should be handled better.

**Comment by kevinmarlis** [comment]
Closing the loop on the `SSMIS_OSI-401-b` bug...the `401-d` version of the data is available in the same location as `401-b`, so any new granules being downloaded are the `401-d` versions, which don't contain the `confidence_level` variable.

**Comment by kevinmarlis** [comment]
Fix has already been implemented. We first check if the field is in the data's data variables _prior_ to where we index the data from the field name:
https://github.com/ECCO-GROUP/ECCO-pipeline/blob/544ad2982434eec2d886a96cba35df941e2d21fd/ecco_pipeline/transformations/transformation.py#L243
